{
 "title": "VulnerableApp Observability",
 "tags": [
  "VulnerableApp",
  "Loki",
  "Promtail",
  "SEGG-U2-P4H"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "VulnerableApp - todos los registros",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"vulnerableapp\"}"
    }
   ]
  },
  {
   "title": "Security - SQL Injection y XSS",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"vulnerableapp\", log_type=\"Security\"}"
    }
   ]
  },
  {
   "title": "Audit - autenticación",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"vulnerableapp\", log_type=\"Audit\"}"
    }
   ]
  }
 ]
}