{
 "title": "VulnerableApp LogQL Security Monitoring",
 "tags": [
  "VulnerableApp",
  "LogQL",
  "Security",
  "SEGG-U2-P4H-3"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Errores - level=ERR",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"VulnerableApp\", environment=\"dev\", level=\"ERR\"}"
    }
   ]
  },
  {
   "title": "Autenticaciones fallidas",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{application=\"VulnerableApp\", environment=\"dev\", module=\"authentication\"} |= \"Autenticacion fallida\""
    }
   ]
  },
  {
   "title": "Auditoría - module=authentication",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{application=\"VulnerableApp\", environment=\"dev\", log_type=\"Audit\", module=\"authentication\"}"
    }
   ]
  },
  {
   "title": "Errores críticos y excepciones",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{application=\"VulnerableApp\", environment=\"dev\"} |~ \"(ERR|Exception|excepcion|InvalidOperationException|500)\""
    }
   ]
  }
 ]
}