// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VulnerableApp.Data;

#nullable disable

namespace VulnerableApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260606023500_SecureRemediation")]
    partial class SecureRemediation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VulnerableApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 1000m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "admin@test.com",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuuD7r1iou4Nkda8bawO9Sa8HY8tugj9ba",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 500m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user@test.com",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuuN8hM0Lie0.O7wznMeu.K7hWZUu6ZDQa",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 750m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Email = "user2@test.com",
                            PasswordHash = "$2a$11$abcdefghijklmnopqrstuuI5mYSFuFNN98A/6se3.SVFJAGDoYqvy",
                            Username = "user2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
